stages:
  - build

build-frontend:
  stage: build
  image: node:latest
  services:
    - docker:24.0.5-dind
  cache:
    - key: "$CI_PROJECT_NAME"
      policy: push
  script:
    - cp .env.staging .env
    - npm install
    - npm run build
  tags:
    - docker
  artifacts:
    paths:
      - public
      - node_modules
    expire_in: 1 day

build-backend:
  stage: build
  services:
    - docker:24.0.5-dind
  cache:
    - key: "$CI_PROJECT_NAME"
      policy: push
  script:
    - cp .env.staging .env
    - composer install
  tags:
    - docker
  artifacts:
    paths:
      - vendor
      - .env
    expire_in: 1 day
