services:
    meetzy_backend:
        container_name: meetzy_backend
        user: "1000:1000"
        build:
            context: .
            target: meetzy_backend
        volumes:
            - './:/opt/meetzy/'
            - './.docker/supervisor/conf.d:/etc/supervisor/conf.d'
            - './.docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            COUNTRIES_JSON: "countries.json"
            CITIES_JSON: "cities.json"
        networks:
            - meetzy_network
        ports:
            - '8080:8080'
        dns:
            - 8.8.8.8
            - 4.4.4.4

    meetzy_web_server:
        container_name: meetzy_web_server
        build:
            context: .
            target: meetzy_web_server
        ports:
            - '${DEPLOY_PORT}:80'
        environment:
            FPM_HOST: "meetzy_backend:9000"
            WEBSOCKET_HOST: "meetzy_backend:8080"
        volumes:
            - './public:/opt/meetzy/public'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - meetzy_network
        tty: true

    meetzy_redis:
        container_name: meetzy_redis
        image: 'redis:7.2.4-alpine'
        ports:
            - '8307:6379'
        networks:
            - meetzy_network

    meetzy_database:
        image: 'mariadb:latest'
        container_name: meetzy_database
        ports:
            - '8306:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_HOST: '%'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
        volumes:
            - meetzy-database:/var/lib/mysql/
        networks:
            - meetzy_network

    meetzy_mailhog:
        container_name: meetzy_mailhog
        image: 'mailhog/mailhog'
        ports:
            - '2025:1025'
            - '9025:8025'
        networks:
            - meetzy_network

    meetzyminio:
        container_name: meetzyminio
        image: minio/minio:latest
        ports:
            - "9000:9000"
            - "9001:9001" # MinIO Console Port
        environment:
            MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
            MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
        volumes:
            - minio-data:/data
        command: server /data --console-address ":9001"
        networks:
            - meetzy_network

    meetzy_mongo:
        container_name: meetzy_mongo
        image: 'mongo:6.0'
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_INITDB_ROOT_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_INITDB_ROOT_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_INITDB_DATABASE}'
        volumes:
            - mongodb-data:/data/db
        networks:
            - meetzy_network

networks:
    meetzy_network:

volumes:
    meetzy-database:
        driver: local
    localstack-data:
        driver: local
    minio-data:
        driver: local
    mongodb-data:
        driver: local
